- name: (tmp for Ubuntu 22.04) Add liburcu6 repository into sources.list
  become: true
  ansible.builtin.apt_repository:
    repo: deb http://jp.archive.ubuntu.com/ubuntu/ impish main restricted
    filename: impish
    state: present

- name: Get CUDA architecture name
  ansible.builtin.shell: |
    if [ "$(uname -m)" = "x86_64" ]; then
      echo "x86_64"
    else
      echo "sbsa"
    fi
  register: cuda_architecture
  changed_when: false

- name: Install CUDA keyring
  become: true
  ansible.builtin.apt:
    deb: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/{{ cuda_architecture.stdout }}/cuda-keyring_1.0-1_all.deb
    update_cache: true

- name: Get dash-case name of cuda_version
  ansible.builtin.shell: bash -c 'sed -e "s/\./-/g" <<< $(echo {{ cuda_version }})'
  register: dash_case_cuda_version
  changed_when: false

- name: Install cuda-{{ dash_case_cuda_version.stdout }}
  become: true
  ansible.builtin.apt:
    name: cuda-{{ dash_case_cuda_version.stdout }}
    update_cache: true

- name: Add PATH to .bashrc
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: export PATH="/usr/local/cuda/bin:$PATH"
    state: present
    create: true
    mode: 0644

- name: Add LD_LIBRARY_PATH to bashrc
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: export LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
    state: present
    create: true
    mode: 0644
